In [99]:
import numpy as np
a_30= np.array([0,1,2,3,4])
print (a_30)
b_30= np.array ([[5,6,7,8],[9,10,11,12]])
c_30= np.array ([[[1,1,2,0],[3,2,4,1],[0,0,7,8]],[[4,4,5,1],[8,4,2,3],[3,7,8,7]]])
print(b_30)
print(c_30)
c_30[1,2,0:2]

[0 1 2 3 4]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[[1 1 2 0]
  [3 2 4 1]
  [0 0 7 8]]

 [[4 4 5 1]
  [8 4 2 3]
  [3 7 8 7]]]


array([3, 7])

In [14]:
b_30.ndim

(2, 3, 4)

In [8]:
np.full((5,3),6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [128]:
nangka_30 = np.ones((5,5))
semangka_30 = np.identity(5)*4
apel_30 = 5*semangka_30
total_30 = nangka_30-semangka_30
print(total_30)
apel_30[0:5] = semangka_30
print(apel_30)

[[-3.  1.  1.  1.  1.]
 [ 1. -3.  1.  1.  1.]
 [ 1.  1. -3.  1.  1.]
 [ 1.  1.  1. -3.  1.]
 [ 1.  1.  1.  1. -3.]]
[[4. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0.]
 [0. 0. 4. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 4.]]


In [101]:
x_30 = np.random.randint(3,14,size = (5,5))
print(x_30)
y_30 = 2/x_30
print(y_30)
z_30 = x_30.copy()
print(z_30)
z_30[0] = 6
print(z_30)

[[ 4  4  6  7 11]
 [ 5 12  3  7 11]
 [10 11  6  7  9]
 [ 9  7  9  3 10]
 [ 4  3  6  9  7]]
[[0.5        0.5        0.33333333 0.28571429 0.18181818]
 [0.4        0.16666667 0.66666667 0.28571429 0.18181818]
 [0.2        0.18181818 0.33333333 0.28571429 0.22222222]
 [0.22222222 0.28571429 0.22222222 0.66666667 0.2       ]
 [0.5        0.66666667 0.33333333 0.22222222 0.28571429]]
[[ 4  4  6  7 11]
 [ 5 12  3  7 11]
 [10 11  6  7  9]
 [ 9  7  9  3 10]
 [ 4  3  6  9  7]]
[[ 6  6  6  6  6]
 [ 5 12  3  7 11]
 [10 11  6  7  9]
 [ 9  7  9  3 10]
 [ 4  3  6  9  7]]


In [102]:
A_30 = np.array([15,30,45,60,75])
B_30 = np.array([90,120,135,150,180])
print(A_30)
C_30 = np.matmul(A_30,B_30)
print(C_30)

[15 30 45 60 75]
33525


In [120]:
np.tanh(A_30)

array([1., 1., 1., 1., 1.])

In [118]:
red_30 = np.array([[2,4,6,8,10],[12,14,16,18,20],
                  [22,24,26,28,30],[32,34,36,38,40]])
print(red_30)
yellow_30 = np.max(red_30)
print(yellow_30)
blue_30 = np.max(red_30,axis=0)
print(blue_30)
green_30 = np.min(red_30,axis=1)
print(green_30)
white_30 = np.sum(red_30)
print(white_30)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]
40
[32 34 36 38 40]
[ 2 12 22 32]
420
